# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Moya', '~> 14.0'
  pod 'RealmSwift'

  # Pods for MVVMDemo

  target 'MVVMDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVMDemoUITests' do
    # Pods for testing
  end

end
